baseURL = 'https://blog.dpinkerton.com/'
languageCode = 'en-us'
title = 'David Pinkerton'
theme = 'PaperMod'
timeZone = 'Australia/Sydney'

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  disableSpecial1stPost = true

  [params.homeInfoParams]
    Title = "David Pinkerton"
    Content = "Systems thinking applied to servers, sats, and sets."

  [[params.socialIcons]]
    name = "nostr"
    title = "Nostr"
    url = "https://njump.me/npub1jz0rlhp9ngs3at2kfhzcnc62sxh0y9rxt40x3z003wmdguljky9quaaju6"

  [[params.socialIcons]]
    name = "email"
    title = "Email"
    url = "mailto:blog@dpinkerton.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
